# ACTIVE DIRECTORY (DOMAIN CONTROLLER)

[WinEventLog://Security]
disabled = 0
index = ad
renderXml = true
checkpointInterval = 5

[WinEventLog://Directory Service]
disabled = 0
index = ad

[WinEventLog://DNS Server]
disabled = 0
index = ad
