[windows]
homePath   = /opt/splunk/var/lib/splunk/windows/db
coldPath   = /opt/splunk/var/lib/splunk/windows/colddb
thawedPath = /opt/splunk/var/lib/splunk/windows/thaweddb
maxDataSize = auto
frozenTimePeriodInSecs = 2592000 
# 30 days retention

[sysmon]
homePath   = /opt/splunk/var/lib/splunk/sysmon/db
coldPath   = /opt/splunk/var/lib/splunk/sysmon/colddb
thawedPath = /opt/splunk/var/lib/splunk/sysmon/thaweddb
maxDataSize = auto
frozenTimePeriodInSecs = 2592000

[vpn]
homePath   = /opt/splunk/var/lib/splunk/vpn/db
coldPath   = /opt/splunk/var/lib/splunk/vpn/colddb
thawedPath = /opt/splunk/var/lib/splunk/vpn/thaweddb
maxDataSize = auto
frozenTimePeriodInSecs = 2592000

[ad]
homePath   = /opt/splunk/var/lib/splunk/ad/db
coldPath   = /opt/splunk/var/lib/splunk/ad/colddb
thawedPath = /opt/splunk/var/lib/splunk/ad/thaweddb
maxDataSize = auto
frozenTimePeriodInSecs = 2592000