# WINDOWS ENDPOINT LOGS

[WinEventLog://Security]
disabled = 0
index = windows
renderXml = true
checkpointInterval = 5

[WinEventLog://System]
disabled = 0
index = windows

[WinEventLog://Application]
disabled = 0
index = windows


# SYSMON TELEMETRY

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = sysmon
renderXml = true
checkpointInterval = 5


# POWERSHELL LOGGING

[WinEventLog://Microsoft-Windows-PowerShell/Operational]
disabled = 0
index = windows
renderXml = true

[WinEventLog://Windows PowerShell]
disabled = 0
index = windows